import a_prototypeObject from './a_prototypeObject';
import b_fPrototype from './b_fPrototype';
import c_BuiltInClasses from './c_BuiltInClasses';
import d_nativePrototypes from './d_nativePrototypes';
import e_theirClassesOnPrototypes from './e_theirClassesOnPrototypes';
import f_classInheritance from './f_classInheritance';
import g_checkClassInstanceOf from './g_checkClassInstanceOf';
import h_itsErrorsInheritanceFromError from './h_itsErrorsInheritanceFromError';
import i_mixins from './i_mixins';